spring.threads.virtual.enabled=true
spring.datasource.url=jdbc:sqlite:aura.db
spring.datasource.driver-class-name=org.sqlite.JDBC
target.server.url=${target.webui.url}/v1
target.webui.url=http://192.168.1.114:8080
target.server.restart-script=C:\\ai\\run 27b.bat
target.server.restart-commands=C:\\ai\\run 27b.bat, C:\\ai\\run 70b.bat
server.port=8081

# Llama.cpp Update Configuration
llama.cpp.install.dir=C:/ai/llama
llama.cpp.release.regex=^llama-.*-bin-win-cuda-13\\.3-x64\\.zip$

# Suppress OSHI WMI warnings
logging.level.oshi=ERROR

# Hardware Monitor Polling Interval (in milliseconds)
hardware.monitor.interval=5000
